### ISSUE TITLE
issue with lambdas and primitives

### ISSUE THREAD

**Issue by jkbits1** [yesco/esp-lisp#6]
Hi, 

I've come across some interesting behaviour with lambdas and PRIMitives.

Specifically, it relates to primitives that expect the lisp env as the first param, and are defined with 
DEFPRIM (envPrimName, negative value, codePrimName).

As I found the issue when creating my own primitives, there are two sets of tests below. The first set works with the master code as it is now. The second set works with a branch of my forked repo (the only code changes in this branch relate to the tests here).

https://github.com/jkbits1/esp-lisp/tree/lambda-param-issue

```
First Tests

Define a global var *intEvent04*, set to initial value
(set! *intEvent04* 0)

Define two lambda functions
(define sb  (lambda (n) (set! *intEvent04* n)))
(define sb2 (lambda (s n) (set! s n)))                   

Execute tests
(set! *intEvent04* 2) - works, *intEvent04* is set to 2
(sb 3)                     - works, *intEvent04* is set to 3
(sb2 *intEvent04* 4) - fails, global var unchanged


Second tests (using repo branch above)

Define global var *intEvent04* as for first tests

The PRIMitive intChange changes *intEvent04* when the first argument is 4.

Define lambda functions
(define ic (lambda (m n) (intChange 4 n))) 
(define ic2 (lambda (m n) (intChange m n)))             

Execute tests
(intChange 4 5) - works, *intEvent04* is set to 5
(ic 4 6)             - works, *intEvent04* is set to 6
(ic2 4 7)           - fails, global var unchanged
```

General thoughts

1) This behaviour seems to be due to something in primapply(), but I haven't been able to work this out further. I experimented with adding parameters to my primitive in case one of the optimisations was the cause, but this made no difference.

2) The workaround for my code is to declare a PRIMitive that does not expect the global env as a param. Instead the global env is obtained from the C variable.

**Comment by yesco** [comment]
In init add the following line (enable):

```
DEFPRIM(set, -2, _set);
```

lisp> (define _a_ 0)
0
lisp> (define (sb n) (set! _a_ n))
#sb
lisp> (define (sb2 s n) (set s n))
#sb2
lisp> _a_
0
lisp> (sb 3)
3
lisp> _a_
3
lisp> (sb2 '_a_ 7)
7
lisp> _a_
7
lisp> (define (sbx s n) (print s) (set! s n) (print s) (print _a_))
#sb3
lisp> (sbx _a_ 99)

7
99
7 7

Consider that set! "quotes" its first argument..., thus it takes the
variable that literally exists with that name.

In your sb2, sb2 is a normal function thus all arguments is evalutated
first:
_a_ becomes 7 above because we set that value before, so "s" is actually
value 7.

(set! 7 99), hehe, is not really doing anything...

So, you can use "set" it'll evaluate both arguments, but it means you need
quote it before passing in to function.

Try doing
lisp> trace on
lisp> (define (sb2 s n) (set! s n) (set! s (+ n n)) (set! s (\* 3 n)) s)
lisp> (sb2 _a_ 1111)

Here's some play with set and set!

lisp> (define _a_ 0)
0
lisp> _a_
0
lisp> (set! _a_ 1)
1
lisp> _a_
1
lisp> (set '_a_ 2)
2
lisp> _a_
2
lisp> (define _b_ 7)
7
lisp> (define v '_a_)
_a_
lisp> (set v 3)
3
lisp> _a_
3
lisp> _b_
7
lisp> (define x 'v)
v
lisp> (set x '_b_)
_b_
lisp> _a_
3
lisp> _b_
7
lisp> v
_b_
lisp> x
v
lisp> (set v 200)
200
lisp> _a_
3
lisp> _b_
200
lisp> v
_b_
lisp> x
v
lisp>

On Tue, Jun 7, 2016 at 7:53 AM, Jon Kelly notifications@github.com wrote:

> Hi,
> 
> I've come across some interesting behaviour with lambdas and PRIMitives.
> 
> Specifically, it relates to primitives that expect the lisp env as the
> first param, and are defined with
> DEFPRIM (envPrimName, negative value, codePrimName).
> 
> As I found the issue when creating my own primitives, there are two sets
> of tests below. The first set works with the master code as it is now. The
> second set works with a branch of my forked repo (the only code changes in
> this branch relate to the tests here).
> 
> https://github.com/jkbits1/esp-lisp/tree/lambda-param-issue
> 
> First Tests
> 
> Define a global var _intEvent04_, set to initial value
> (set! _intEvent04_ 0)
> 
> Define two lambda functions
> (define sb  (lambda (n) (set! _intEvent04_ n)))
> (define sb2 (lambda (s n) (set! s n)))
> 
> Execute tests
> (set! _intEvent04_ 2) - works, _intEvent04_ is set to 2
> (sb 3)                     - works, _intEvent04_ is set to 3
> (sb2 _intEvent04_ 4) - fails, global var unchanged
> 
> Second tests (using repo branch above)
> 
> Define global var _intEvent04_ as for first tests
> 
> The PRIMitive intChange changes _intEvent04_ when the first argument is 4.
> 
> Define lambda functions
> (define ic (lambda (m n) (intChange 4 n)))
> (define ic2 (lambda (m n) (intChange m n)))
> 
> Execute tests
> (intChange 4 5) - works, _intEvent04_ is set to 5
> (ic 4 6)             - works, _intEvent04_ is set to 6
> (ic2 4 7)           - fails, global var unchanged
> 
> General thoughts
> 
> 1) This behaviour seems to be due to something in primapply(), but I
> haven't been able to work this out further. I experimented with adding
> parameters to my primitive in case one of the optimisations was the cause,
> but this made no difference.
> 
> 2) The workaround for my code is to declare a PRIMitive that does not
> expect the global env as a param. Instead the global env is obtained from
> the C variable.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/yesco/esp-lisp/issues/6, or mute the thread
> https://github.com/notifications/unsubscribe/ACBfmhwwaEKQzmQIpH0QUvXW2KTyuzdRks5qJLLvgaJpZM4IvbWd
> .

## 

.sigh

**Comment by jkbits1** [comment]
@yesco thank you very much for this response, it's very helpful indeed !!

I'll add set to my implementation and go through the lessons above to improve my understanding of lisp quoting. I know the rules, but they aren't automatic for me yet.

Just to check, in my second tests, I'm using my own primitive exposed to the lisp env with DEFPRIM(..., -2, ...). That function just expects a number (so not a var name), which doesn't get through. Should I just steer clear of defining my primitives this way, and use my workaround (mentioned at the very end of my original text)? 

Thanks again !

**Comment by yesco** [comment]
Quoting is interesting, now. the negative argument is essentially my way of
defining a "special form" which means the given arguments are not evaluated.

I changed your functions to print out their arguments (see below), then I
did "trace on".

lisp> trace on
..
lisp> (ic 4 6)
---> (ic 4 6)
     ENV fibo=#fibo
  ---> (intChange 4 n)
       ENV n=6 m=4 fibo=#fibo
_PIN=4 v=_
_n pinNum=4 value=_
n HERE4
BIND=(_intEvent04_)  v=
6   n <--- (#intChange 4 n)
n <--- (#ic 4 6)
n
lisp> (ic2 4 6)
---> (ic2 4 6)
     ENV fibo=#fibo
  ---> (intChange m n)
       ENV n=6 m=4 fibo=#fibo
_PIN=m v=_
_n pinNum=0 value=_
n BIND=(_intEvent00_)  v=
6   n <--- (#intChange m n)
n <--- (#ic2 4 6)
n
inline PRIM _setbang(lisp\* envp, lisp name, lisp v) {
    if (!symbolp(name)) { printf("set! of non symbol="); prin1(name);
terpri(); error("set! of non atom: "); }
    lisp bind = _setqqbind(envp, name, nil, 0);
    // TODO: evalGC? probably safe as steqqbind changed an existing env

```
// eval using our own named binding to enable recursion

v = eval(v, envp);
printf("BIND="); princ(bind); printf("  v="); print(v);
setcdr(bind, v);

return v;
```

}

PRIM _setbang(lisp\* envp, lisp name, lisp v);

PRIM intChange(lisp\* envp, lisp pin, lisp v) {
    int pinNum = getint(pin);
    printf("PIN="); princ(pin); printf(" v="); print(v);
    printf("pinNum=%d value=", pinNum);
    print(v);

```
if (pinNum == 4) {
    printf("HERE4\n");
    _setbang(envp, symbol("*intEvent04*"), v);
}
else if (pinNum == 2) {
    _setbang(envp, symbol("*intEvent02*"), v);
}
else {
    _setbang(envp, symbol("*intEvent00*"), v);
}

return v;
```

}

--- You see how pin=m ?

it's given the symbol as intChange doesn't eval it argument
(in setbang it's done by ..   v = eval(v, envp); ... )

So getint(symbol('m')) ==> 0,,

thus it tries to set _intEvent00_ which isn't declared.

---

Using these non-eval functions are tricky. It's kind of like
macros but different. NLAMBDA some call them, no-eval lambdas.

Usually, it's better not to add these functions unless it adds elegance
or simplicity to something you do very often, things one type on the
keyboard,
or new constructs like if/de/define/while/loop etc...

You can fix your code by changing:

  int pinNum = getint(eval(pin, envp));

However, the best cause of action would be to quote the name and use
the "set" function. I've enabled it by default.

Some other hints:
1. please define all "global" variables on toplevel before using (define
   _intEvent04_ 0)...
2. print is your help... so is printf..., it's how to figure out what
   happens.
3. "trace on" is cool for lisp-only code
4. symbol names (as well as function names) which are only 6 chars long and
   only of a-z0-9_-?/ don't take any "heap" space at all. Also, they're faster
   to calculate.
   I'll add set to my implementation and go through the lessons above to
   improve my understanding of lisp quoting. I know the rules, but they aren't
   automatic for me yet.

memory usage can be checked with:
lisp> mem '_foo_
     total:   1 allocations of    22 bytes, and still use  -1 total    14
bytes
lisp> mem '_foo_
... (nothing allocated, since the symbol already exist)
lisp> mem '_bar_
       total:   1 allocations of    22 bytes, and still use   1 total    22
bytes
lisp> mem 'foo
... (no allocations)
lisp> mem 'foobar
... same
lisp> mem 'foobarx
  total:   1 allocations of    24 bytes, and still use   1 total    24 bytes

since '*' is not in the list above, it'll be allocated on the heap, so maybe
define the variables. Alternative is names that are any 3 character long,
they also don't take any heapspace. The reason to do this, especially for
features which everyone may want to have, is that there is then very little
overhead for functions/names/symbols not used.

Please note that \* variables are nothing special, they aren't dynamic or
global or anything, just different character in name, in this lisp...

(define _p0 0)
(define _p2 0)
(define _p4 0)

---------------- so regarding your question:

> General thoughts
> 
> 1) This behaviour seems to be due to something in primapply(), but I
> haven't been
> able to work this out further. I experimented with adding parameters to
> my primitive
> in case one of the optimisations was the cause, but this made no
> difference.

special forms like if/cond/de/define are tricks of mind, eval/apply/quote
etc are diferent levels of thinking. Like FORTH where you have 3 levels!
(compile time, runtime, delayed compile) - even more fun!

> 2) The workaround for my code is to declare a PRIMitive that does not
> expect the
> global env as a param. Instead the global env is obtained from the C
> variable.

So we found out that this was not the issue, in general don't try to get
hold of global C variables... Please not that the "env" given to a -2
primfunction is not the global env. It's actually a "local" one for that
function invocation. You can (print (env)) to see what it is! (or just
"trace on"). Any variable that you set! which aren't global will be set in
the local env, that's why it's good to define globals at top level.

Now, let's get back to why you may need this function, it's to be called in
the interrupt handler?

Maybe you want me to look at your interrupt handler now, see if I have any
hints...

cheers,
   Jonas

On Wed, Jun 8, 2016 at 3:48 AM, Jon Kelly notifications@github.com wrote:

> @yesco https://github.com/yesco thank you very much for this response,
> it's very helpful indeed !!
> 
> I'll add set to my implementation and go through the lessons above to
> improve my understanding of lisp quoting. I know the rules, but they aren't
> automatic for me yet.
> 
> Just to check, in my second tests, I'm using my own primitive exposed to
> the lisp env with DEFPRIM(..., -2, ...). That function just expects a
> number (so not a var name), which doesn't get through. Should I just steer
> clear of defining my primitives this way, and use my workaround (mentioned
> at the very end of my original text)?
> 
> Thanks again !
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/yesco/esp-lisp/issues/6#issuecomment-224393238, or mute
> the thread
> https://github.com/notifications/unsubscribe/ACBfmqkrH1m_5Ok3fGRTdPYeMcaQ2IbJks5qJcsggaJpZM4IvbWd
> .

## 

.sigh

**Comment by jkbits1** [comment]
Once again, thank you very much for this, it is appreciated as it teaches me a lot !

It's quite a few years since I did anything with lisp, and although I've read up on quoting and lisp generally, many of the patterns are not automatic for me yet. And the patterns are maybe more subtle and varied than I realised !

I did study this behaviour for quite some time, but using printf only, not print. 

Yes, this is a function for the interrupt handler. It is a nice to have item though, rather than a necessity. It avoids pasting in a define (from a text file where I have a bunch of them). The global env hack was only considered because these var names should only exist at global level, and not in any other lexical context/closure.

Interrupt handler code will arrive very soon !
